// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6d1oSIrY9XpxTq-ExrbddFfGhibBpDCQ',
    appId: '1:265921138811:web:d278a9e65547ebbabcd2de',
    messagingSenderId: '265921138811',
    projectId: 'jagvault-5604b',
    authDomain: 'jagvault-5604b.firebaseapp.com',
    storageBucket: 'jagvault-5604b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAagfxFC5w6TDvEV57U_1suAiCMqtoA7CE',
    appId: '1:265921138811:android:157c08c8105f0ba4bcd2de',
    messagingSenderId: '265921138811',
    projectId: 'jagvault-5604b',
    storageBucket: 'jagvault-5604b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRGWaNuBod6yx85_R8akoFHpSjGwBuI0A',
    appId: '1:265921138811:ios:ba76fda43d89461bbcd2de',
    messagingSenderId: '265921138811',
    projectId: 'jagvault-5604b',
    storageBucket: 'jagvault-5604b.appspot.com',
    iosClientId:
        '265921138811-7v1j1uuf5thpeugf11ahtn0a0vnvcs95.apps.googleusercontent.com',
    iosBundleId: 'com.example.jagvault',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRGWaNuBod6yx85_R8akoFHpSjGwBuI0A',
    appId: '1:265921138811:ios:ba76fda43d89461bbcd2de',
    messagingSenderId: '265921138811',
    projectId: 'jagvault-5604b',
    storageBucket: 'jagvault-5604b.appspot.com',
    iosClientId:
        '265921138811-7v1j1uuf5thpeugf11ahtn0a0vnvcs95.apps.googleusercontent.com',
    iosBundleId: 'com.example.jagvault',
  );
}
